Update deploy-standalone-plugins.yml

diff --git a/.github/workflows/deploy-standalone-plugins.yml b/.github/workflows/deploy-standalone-plugins.yml
--- a/.github/workflows/deploy-standalone-plugins.yml
+++ b/.github/workflows/deploy-standalone-plugins.yml
@@ -57,8 +57,13 @@ jobs:
           if ${{ github.event_name == 'workflow_dispatch' }}; then
             echo "Manual"
             echo "${{ steps.get-version.outputs.version }}"
-            # Set the manual input values in JSON format for use in the matrix.
-            echo "matrix={\"include\":[{\"slug\":\"${{ inputs.slug }}\",\"version\":\"${{ steps.get-version.outputs.version }}\"}]}" >> $GITHUB_OUTPUT
+            if ${{ steps.get-version.outputs.version }} == ''; then
+              echo "The ${{ inputs.slug }} module slug is missing in the file plugins.json."
+              exit 1
+            else
+              # Set the manual input values in JSON format for use in the matrix.
+              echo "matrix={\"include\":[{\"slug\":\"${{ inputs.slug }}\",\"version\":\"${{ steps.get-version.outputs.version }}\"}]}" >> $GITHUB_OUTPUT
+            fi
           else
             echo "Auto"
             # Load the JSON file and parse from "{name: {slug, version}, ...}" to "include: [{ name, slug, version }, ...]"
