User regex

diff --git a/.github/workflows/deploy-standalone-plugins.yml b/.github/workflows/deploy-standalone-plugins.yml
--- a/.github/workflows/deploy-standalone-plugins.yml
+++ b/.github/workflows/deploy-standalone-plugins.yml
@@ -56,6 +56,13 @@ jobs:
         run: |
           if ${{ github.event_name == 'workflow_dispatch' }}; then
             echo "Manual"
+            if ${{ steps.get-version.outputs.version }} =~ ^(\*|\d+(\.\d+){0,2}(-[a-zA-Z0-9\.]+)?)$; then
+              echo "The ${{ inputs.slug }} module slug is in the file plugins.json."
+              exit 1
+            else
+              echo "The ${{ inputs.slug }} module slug is missing in the file plugins.json."
+              exit 1
+            fi
             echo "${{ steps.get-version.outputs.version }}"
             if ${{ steps.get-version.outputs.version == '' }}; then
               echo "The ${{ inputs.slug }} module slug is missing in the file plugins.json."
